export enum Raum {
    null="",
    klasse1="Kl.1",
    klasse2="Kl.2",
    klasse3="Kl.3",
    klasse4="Kl.4",
    klasse5="Kl.5",
    klasse6="Kl.6",
    klasse7="Kl.7",
    klasse8="Kl.8",
    klasse9="Kl.9",
    klasse10="Kl.10",
    klasse11="Kl.11",
    klasse12="Kl.12",
    klasse13="Kl.13",
    handarbeit1="Handarb.1",
    handarbeit2="Handarb.2",
    handarbeit3="Handarb.3",
    physik="Phys",
    chemie="Chem",
    computterraumschueler="Comp.",
    nebenraumKlasse10="neben Kl.10"
}
